### PR TITLE
Fix typo in compiler error message

### PR DESCRIPTION
**Pull request by mfaerevaag**
Just a small typo, but thought I would report it :smile:

### CODE REVIEW

**Comment by sangkilc** [comment]
Why here?

**Comment by mfaerevaag** [comment]
Is this the wrong place to make a PR or shouldn't I have made a PR in the first place? The activity said to make pull request if you made any "optimizations". Although this is no optimization, I though it was the right thing to do.

**Comment by sangkilc** [comment]
Why don't you create a PR for the main repo: https://github.com/KAIST-IS521/mini-vm

**Comment by mfaerevaag** [comment]
Sorry, I'll that instead.

**Pull request closed without merging**
